#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso utilities
wclean libso FunctionObjects/ExaCA
wclean libso FunctionObjects/unmappedSolidificationFields
wclean libso FunctionObjects/stork
wclean libso FunctionObjects/timeAboveMelting
wclean libso movingHeatSource
wclean

#------------------------------------------------------------------------------
