#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso utilities
wclean libso FunctionObjects
wclean libso movingHeatSource
wclean

#------------------------------------------------------------------------------
